services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # management UI
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      -  app-net

  file_upload:
    build:
      context: .
      dockerfile: file_upload/Dockerfile.file_upload
    volumes:
      - ./data:/data
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      RABBITMQ_QUEUE: file_queue
      FILE_PATH: /data
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      -  app-net

  batch_process:
    build:
      context: .
      dockerfile: batch_process/Dockerfile.batch_process
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_QUEUE: file_queue
      API_HOST: 0.0.0.0
      API_PORT: 5000
      FILE_PATH: /data
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      -  app-net

networks:
  app-net:
    driver: bridge